package kz.flabs.parser;

public enum FormulaBlockType {
	SYSTEM_FIELD_NAME, SYSTEM_FIELD_CONDITION, SYSTEM_FIELD_VALUE, FIELDNAME, CONDITION,VALUE,BOOLOPERAND,OPENBRACKED,CLOSEBRACKED,END,PARAMETER;
}
