package kz.flabs.webrule.constants;

public enum ValueSourceType {
	STATIC, @Deprecated QUERY, @Deprecated SCRIPT, REGISTER, MACRO, DOCFIELD, DOC_FIELD, DOC_ATTACHMENT, KEYWORD, WEBFORMFIELD, UNKNOWN, WEBFORMFILE, DOGFORMULA, DOMINOFIELD, PARENTDOCFIELD, DEPARTMENTID, MAINDOCFIELD, RESULTSET, VOCABULARY, FILE, GROOVY_FILE, JAVA_CLASS

}
