package kz.flabs.users;

public enum AuthFailedExceptionType {
	NO_USER_SESSION, PASSWORD_INCORRECT, ANSWER_WRONG, UNANSWERED_QUESTION, SYSTEM_DATABASE_HAS_NOT_ANSWERED, NO_ASSOCIATED_SESSION_FOR_THE_TOKEN
}
