package kz.flabs.exception;

public enum DocumentExceptionType {
	RUNTIME_ERROR, UNKNOW_DOCUMENT_TYPE, FIELD_NOT_FOUND, DATE_VALUE_INCORRECT, NUMBER_VALUE_INCORRECT, 
	ERROR_RECOVERY_PROCESS, CANNOT_GET_VALUE_AS_DATA, ATTACHMENT_FIELD_NOT_FOUND, 
	VALUE_TOO_LONG, CANNOT_GET_PARENT_DOCUMENT_FROM_NEWDOC, COMPLEX_OBJECT_INCORRECT;
}
