package kz.flabs.dataengine.h2.usersactivity;

public class UsersActivityDDEScripts {

    public static String getUsersActivityDDE() {
        String dde = "create table USERS_ACTIVITY(ID int generated by default as identity PRIMARY KEY, " +
                " TYPE int NOT NULL," +
                " DBID varchar(32), " +
                " USERID varchar(32), " +
                " CLIENTIP char(15), " +
                " EVENTTIME timestamp," +
                " DOCID int NOT NULL," +
                " DOCTYPE int NOT NULL," +
                " DDBID varchar(16)," +
                " VIEWTEXT varchar(2048))";
        return dde;
    }

    public static String getUsersActivityChangesDDE() {
        String dde = "create table USERS_ACTIVITY_CHANGES(ID int generated by default as identity PRIMARY KEY, " +
                " AID int, " +
                " FIELDNAME  varchar(30), " +
                " OLDVALUE varchar(512), " +
                " NEWVALUE varchar(512), " +
                " FIELDTYPE int, " +
                " FOREIGN KEY (AID) REFERENCES USERS_ACTIVITY(ID) ON DELETE CASCADE)";
        return dde;
    }

    public static String getRecycleBinDDE() {
        String dde = "create table recycle_bin (id int generated by default as identity PRIMARY KEY," +
                " AID int, " +
                " VALUE blob, " +
                " FOREIGN KEY (AID) REFERENCES USERS_ACTIVITY(ID))";
        return dde;
    }

    public static String getActivityDDE() {
        String dde = "CREATE TABLE activity \n" +
                "(\n" +
                "  id bigint generated by default as identity PRIMARY KEY,\n" +
                "  viewtext varchar(2048),\n" +
                "  userid varchar(256),\n" +
                "  parameters varchar(2048),\n" +
                "  ACTIVITY_TYPE boolean,\n" +
                "  RETURN_TIME timestamp,\n" +
                "  EVENT_TIME timestamp, \n" +
                "  COMMENT varchar(1024),\n" +
                "  PROCESSED_REC integer,\n" +
                "  PROCESSED_SIZE integer,\n" +
                "  TRANSACTION varchar(1024),\n" +
                "  SERVICE_NAME varchar(1024),\n" +
                "  REQUEST_TIME timestamp,\n" +
                "  SPRING_SERVER varchar(1024)\n" +
                ")";
        return dde;
    }

	/*public static String getUsersActivityBlobChangesDDE(){
        String dde = "create table USERS_ACTIVITY_BLOBCHANGES (id int generated by default as identity PRIMARY KEY, " +
		"docid int, " +
		"doctype int, " +
		"name varchar(32), " +
		"type int, " +
		"originalname varchar(128), " +
		"cheksum varchar(40), " + 
		"value blob)";
		return dde;
	}*/

}
